# Generated by Django 3.2.16 on 2022-11-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Q1', models.CharField(max_length=50)),
                ('Q2', models.CharField(max_length=50)),
                ('Q3', models.CharField(max_length=50)),
                ('Q4', models.CharField(max_length=50)),
                ('Q5', models.CharField(max_length=50)),
                ('Q6', models.CharField(max_length=50)),
                ('Q7', models.CharField(max_length=50)),
                ('Q8', models.CharField(max_length=50)),
                ('Q9', models.CharField(max_length=50)),
                ('Q10', models.CharField(max_length=50)),
                ('Q11', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
